apiVersion: v1
kind: Service
metadata:
    name: "imovetest1-1022"
    labels:
        app: "imovetest1-1022"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "imovetest1-1022"