

name: Tags

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"
  pull_request:
    tags: 
      - "[0-9].[0-9].[0-9]"
env:
  CARGO_TERM_COLOR: always
jobs:
  package:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}               
      - name: login
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build producer
        run: docker build -t ghcr.io/modulus/version-app:${{ steps.vars.outputs.tag }} -f Dockerfile .
      - name: Docker push
        run: docker push ghcr.io/modulus/version-app:${{ steps.vars.outputs.tag }}
      - name: Docker build consumer
        run: docker build -t ghcr.io/modulus/version-locust:${{ steps.vars.outputs.tag }} -f Dockerfile.locust .
      - name: Push consumer container
        run: docker push ghcr.io/modulus/version-locust:${{ steps.vars.outputs.tag }}   